language: python
python:
  - "3.6"


before_install:
    # Tricks to avoid matplotlib error about X11:
	#https://github.com/pierrepo/PBxplore/blob/master/.travis.yml
    # 'no display name and no $DISPLAY environment variable'
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/#Starting-a-Web-Server
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"


# command to install dependencies
install:
  - pip install -r requirements.txt

script:
    pytest
